feat(rspack): Add extractLicenses option to rspack's project configuration
nrwl/nx-labs pull request #230
Opened 2023-04-24 21:00 UTC by dgmachado

It's related to the ticket: https://github.com/nrwl/nx-labs/issues/219

Obs: Rspack already supports the license-webpack-plugin [Issue](https://github.com/web-infra-dev/rspack/issues/2913). It's required to upgrade the @rspack/core to get the changes implements on https://github.com/web-infra-dev/rspack/pull/3010.

In order to make the tests you can force to use the version @rspack/core:0.1.11

Update (@mandarini) : Once this PR is merged (https://github.com/nrwl/nx-labs/pull/278) we can go ahead and rebase, and then merge!

2023-05-15 18:06 UTC, jaysoo commented
Thanks! I think we should do one of two things:

1. Wait for the feature to be in stable rspack
2. Log a warning to user `logger.warn` if the installed rspack version does not support this feature and disable licenses

Otherwise I the user will get an error when on an latest rspack version.

2023-05-16 09:04 UTC, mandarini requested changes
Hey @dgmachado thanks for the PR! I agree with @jaysoo , so let's please add these fixes (let me know if you need help). Also, I think there are some linting issues. Can you run `nx lint rspack` and see what's wrong?

2023-05-16 21:34 UTC, dgmachado commented
There's a known issue when the perChunkOutput property has a value false but there's an open [PR](https://github.com/web-infra-dev/rspack/pull/3172) to fix this. Probably the fix will be available only on @rspack/core:0.1.12. At the moment I don't see any problem to keep this fixed as true inside the [nx-labs](https://github.com/nrwl/nx-labs) repository.

2023-05-17 21:55 UTC, dgmachado commented
@mandarini @jaysoo the @rspack/core [0.1.11](https://www.npmjs.com/package/@rspack/core/v/0.1.11) has been released

2023-05-18 08:46 UTC, mandarini commented
@dgmachado perfect. I'll test your PR with that version! Thanks

2023-05-19 16:39 UTC, mandarini commented
@dgmachado do you want to update the repo to the latest rspack, and rebase your PR? We can then go ahead and re-test and merge! Sorry about the delay! :)

2023-05-23 08:10 UTC, mandarini approved these changes
Changes look good to me. I will upgrade the repo to latest rspack in another PR, but I agree that for now it's ok to force to true!

2023-05-23 11:45 UTC, mandarini requested changes
Actually, needs rebase with latest `main` after https://github.com/nrwl/nx-labs/pull/278 is merged

2023-05-24 08:41 UTC, mandarini commented
Hello @dgmachado ! Can you please rebase your branch with main, instead of merging main into your branch, for getting the latest changes? This way we can have a cleaner history! :D

2023-05-24 16:13 UTC, mandarini approved these changes

2023-05-24 16:38 UTC, merged